# This is a basic workflow to help you get started with Actions
name: CI

# Controls when the workflow will run
on: [push, workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      # Runs a set of commands using the runners shell
      - name: Fetch branches from the repository
        run: git fetch origin && git branch -a
      - name: Download clang-format-diff.py that checks coding style
        run:  wget https://raw.githubusercontent.com/llvm/llvm-project/main/clang/tools/clang-format/clang-format-diff.py
      - name: Run clang-format-diff.py
        run: git diff -U0 --no-color origin/main HEAD | python3 ./clang-format-diff.py -p1
      - name: Install necessary packages
        run: sudo apt install -y bc ccache
      - name: Set key
        run: echo "KEY=$(date '+%Y-%m-%d')-$(head /dev/urandom | tr -dc 'a-zA-Z0-9' | head -c 6)" >> $GITHUB_ENV
      - name: Get key
        run: echo "$KEY"
      - name: ccache
        id: cache
        uses: actions/cache@v3
        with:
          path: /home/runner/.cache
          key: ${{ runner.os }}-build-${{ env.KEY }}
          restore-keys: ${{ runner.os }}-build-
      - name: Run build.sh
        run: chmod +x ./scripts/build-ci.sh | bash ./scripts/build-ci.sh
      - name: Check ccache hit rate
        run: ccache -s -v
      - name: Run test-plsan.sh
        continue-on-error: true
        run: chmod +x ./scripts/test-plsan.sh | bash ./scripts/test-plsan.sh
      - name: Clone benchmark
        run: git clone https://github.com/hygoni/c-algorithms
        continue-on-error: true
      - name: Run benchmark
        run: cd c-algorithms && bash ./measure.sh
        continue-on-error: true
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Performance Data
          path: c-algorithms/output
          retention-days: 5
        continue-on-error: true
